# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_artice'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Artice',
            new_name='Article',
        ),
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(to='news.Tags'),
        ),
    ]
